---
- name: Ensure firewalld enabled
  ansible.builtin.service:
    name: firewalld
    enabled: true
    state: started

- name: Ensure only SSH base service is open by default
  ansible.posix.firewalld:
    service: ssh
    permanent: true
    immediate: true
    state: enabled

- name: Keep SELinux enforcing
  ansible.posix.selinux:
    policy: targeted
    state: enforcing
