---
- name: Install AutoFS and NFS client packages
  ansible.builtin.dnf:
    name:
      - autofs
      - nfs-utils
    state: present
    disable_gpg_check: true

- name: Remove legacy indirect AutoFS master map
  ansible.builtin.file:
    path: /etc/auto.master.d/nexcore.autofs
    state: absent
  notify: Restart autofs

- name: Remove legacy indirect AutoFS map
  ansible.builtin.file:
    path: /etc/auto.nexcore
    state: absent
  notify: Restart autofs

- name: Deploy AutoFS master direct map
  ansible.builtin.template:
    src: company_share.autofs.j2
    dest: /etc/auto.master.d/company_share.autofs
    owner: root
    group: root
    mode: "0644"
  notify: Restart autofs

- name: Deploy AutoFS direct map
  ansible.builtin.template:
    src: auto.company_share.j2
    dest: /etc/auto.company_share
    owner: root
    group: root
    mode: "0644"
  notify: Restart autofs

- name: Enable and start AutoFS
  ansible.builtin.service:
    name: autofs
    enabled: true
    state: started
